spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      mode: never

  rabbitmq:
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}


rabbit:

  mail-server:
    exchange-name: ${RABBIT_MAIL_SERVER_EXCHANGE_NAME}

    activate-account:
      queue-name: ${RABBIT_MAIL_SERVER_ACTIVATE_ACCOUNT_QUEUE_NAME}
      routing-key: ${RABBIT_MAIL_SERVER_ACTIVATE_ACCOUNT_ROUTING_KEY}


jwt:
  access:
    secret: ${JWT_ACCESS_SECRET}
    expiration-minutes: ${JWT_ACCESS_EXPIRATION_MINUTES}
  refresh:
    secret: ${JWT_REFRESH_SECRET}
    expiration-minutes: ${JWT_REFRESH_EXPIRATION_MINUTES}


accountant:
  username: ${ACCOUNTANT_USERNAME}
  password: ${ACCOUNTANT_PASSWORD}
  email: ${ACCOUNTANT_EMAIL}