package ru.kaplaan.api.domain.user

import org.springframework.security.core.GrantedAuthority

enum class Privilege: GrantedAuthority {

    CREATE_VACANCY, UPDATE_VACANCY, DELETE_VACANCY,
    CREATE_USER_DATA, UPDATE_USER_DATA,
    CREATE_COMPANY_DATA, UPDATE_COMPANY_DATA,
    CREATE_VACANCY_RESPONSE, UPDATE_VACANCY_RESPONSE, DELETE_VACANCY_RESPONSE, GET_VACANCY_RESPONSE_FOR_COMPANY, GET_VACANCY_RESPONSE_FOR_USER,
    CREATE_PAYMENT_INFO, UPDATE_PAYMENT_INFO, GET_PAYMENT_INFO,
    GET_PAYMENT_ORDER_FOR_COMPANY, GET_PAYMENT_ORDER_FOR_ADMIN, UPDATE_PAYMENT_ORDER;

    override fun getAuthority(): String {
        return this.name
    }
}