insert into table role_privilege(role_name, privilege_name)
values
( 'ROLE_USER',  'CREATE_USER_DATA'),
( 'ROLE_USER', 'UPDATE_USER_DATA'),
( 'ROLE_USER', 'CREATE_VACANCY_RESPONSE'),
( 'ROLE_USER',  'VIEW_RESPONSE'),
( 'ROLE_USER',  'GET_VACANCY_RESPONSE_FOR_USER'),

( 'ROLE_COMPANY',  'CREATE_VACANCY'),
( 'ROLE_COMPANY', 'UPDATE_VACANCY'),
( 'ROLE_COMPANY', 'DELETE_VACANCY'),
( 'ROLE_COMPANY',  'CREATE_COMPANY_DATA'),
( 'ROLE_COMPANY', 'UPDATE_COMPANY_DATA'),
( 'ROLE_COMPANY', 'UPDATE_VACANCY_RESPONSE'),
( 'ROLE_COMPANY', 'DELETE_VACANCY_RESPONSE'),
( 'ROLE_COMPANY',  'CREATE_PAYMENT_INFO'),
( 'ROLE_COMPANY', 'UPDATE_PAYMENT_INFO'),
( 'ROLE_COMPANY', 'GET_PAYMENT_ORDER'),
( 'ROLE_COMPANY', 'GET_PAYMENT_INFO'),
( 'ROLE_COMPANY', 'GET_VACANCY_RESPONSE_FOR_COMPANY'),

( 'ROLE_ADMIN',  'UPDATE_PAYMENT_ORDER'),
( 'ROLE_ADMIN',  'GET_PAYMENT_ORDER');