apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server-deployment
  labels:
    app: auth-server
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
        - name: auth-server
          image: auth-server:1
          envFrom:
            - secretRef:
                name: auth-server-secret
            - secretRef:
                name: postgres-auth-secret
            - secretRef:
                name: rabbit-mq-secret
            - secretRef:
                 name: jwt-secret
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: auth-server-service
  labels:
    app: auth-server
spec:
  selector:
    app: auth-server
  ports:
    - port: 3001
      targetPort: 8080
  type: ClusterIP
