apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server-deployment
  labels:
    app: auth-server
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: auth-server-deployment
  template:
    metadata:
      labels:
        app: auth-server-deployment
    spec:
      containers:
        - name: auth-server
          image: auth-server:latest
          envFrom:
            - secretRef:
                name: auth-server-secret
            - secretRef:
                name: postgres-auth-secret
            - secretRef:
                name: rabbit-mq-secret
            - secretRef:
                 name: jwt-secret
          ports:
            - containerPort: 8080
