spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql

  rabbitmq:
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}


rabbit:
  mail-server:
    exchange-name: ${RABBIT_MAIL_SERVER_EXCHANGE_NAME}

    send-vacancy-response:
      queue-name: ${RABBIT_MAIL_SERVER_SEND_VACANCY_RESPONSE_QUEUE_NAME}
      routing-key: ${RABBIT_MAIL_SERVER _SEND_VACANCY_RESPONSE_ROUTING_KEY}

    send-payment-order:
      queue-name: ${RABBIT_MAIL_SERVER_SEND_PAYMENT_ORDER_QUEUE_NAME}
      routing-key: ${RABBIT_MAIL_SERVER_SEND_PAYMENT_ORDER_ROUTING_KEY}

    send-info-about-success-payment:
      queue-name: ${RABBIT_MAIL_SERVER_SEND_INFO_ABOUT_SUCCESS_PAYMENT_QUEUE_NAME}
      routing-key: ${RABBIT_MAIL_SERVER_SEND_INFO_ABOUT_SUCCESS_PAYMENT_ROUTING_KEY}


company-payment-info:
  inn: 1234567890
  kpp: 123456789
  company-name: 'ООО СУПЕРДЖОБ'
  company-account-number: 12345678901234567890
  bank-bik: 123456789
  bank-account-number: 12345678901234567890
  bank-name: 'ООО ТИНЬКОФФ БАНК'
  purpose-of-payment: 'За указание услуг по найму сотрудников'
  sum: 1000

page-size:
  vacancy: 30
  vacancy-response: 30
  payment-order: 30
