apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-mq-deployment
  labels:
    app: rabbit-mq
spec:
  selector:
    matchLabels:
      app: rabbit-mq
  template:
    metadata:
      labels:
        app: rabbit-mq
    spec:
      containers:
        - name: rabbit-mq
          image: rabbitmq:3.13-management
          ports:
            - containerPort: 5672
          volumeMounts:
            - name: rabbit-mq-config-map
              mountPath: /etc/rabbitmq/
      volumes:
        - name: rabbit-mq-config-map
          configMap:
            name: rabbit-mq-config-map

---
apiVersion: v1
kind: Service
metadata:
  name: rabbit-mq-service
  labels:
    app: rabbit-mq
spec:
  type: ClusterIP
  selector:
    app: rabbit-mq
  ports:
    - port: 5672
      targetPort: 5672
